import AuthHeader from "@/component/authentication/AuthHeader/AuthHeader";
import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Neural",
    description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
    return (
        <html lang="en">
            <body>
                <AuthHeader />
                <main className="">
                    <div>
                        {children}
                    </div>
                </main>
            </body>
        </html>
    );
}

