/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/LQGiBIhh47z
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card, CardContent, CardFooter } from "@/components/ui/card"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import { Button } from "@/components/ui/button"

export function Component() {
  return (
    <div className="w-full max-w-md mx-auto">
      <h2 className="text-3xl font-bold mb-6">What's your network talking about</h2>
      <Card className="rounded-lg border border-muted">
        <div className="flex items-center p-4">
          <Avatar>
            <AvatarImage src="/placeholder-user.jpg" alt="James Heathfield" />
            <AvatarFallback>JH</AvatarFallback>
          </Avatar>
          <div className="ml-4">
            <div className="font-bold">James Heathfield</div>
            <div className="text-muted-foreground text-sm">CTO / IBM</div>
          </div>
        </div>
        <CardContent className="p-4">
          <p>
            A botnet is a network of internet-connected devices, each of which is running one or more bots. Botnets can
            be used to perform distributed denial-of-service (DDoS) attacks, steal data, send spam, and allow the
            attacker to access the device and its connection. The owner can control the botnet using command and control
            (C&C) software.
          </p>
        </CardContent>
        <CardFooter className="p-4">
          <Button variant="ghost" size="sm" className="text-muted-foreground">
            <MessageCircleIcon className="w-4 h-4 mr-2" />
            10 Reply
          </Button>
        </CardFooter>
      </Card>
    </div>
  )
}

function MessageCircleIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M7.9 20A9 9 0 1 0 4 16.1L2 22Z" />
    </svg>
  )
}
