import type { Metadata } from "next";
import "./globals.css";
import { nunito } from "./font";
import Footer from "@/component/Footer/Footer";
import Header from "@/component/Header/Header";

export const metadata: Metadata = {
  title: "Neural",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en" className={nunito.className}>
      <body>
        <Header />
        <main className="">
          <div>
            {children}
          </div>
        </main>
        <Footer />
      </body>
    </html>
  );
}

