import type { Metadata } from "next";
import "./globals.css";
import { nunito } from "./font";

export const metadata: Metadata = {
  title: "Neural",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en" className={nunito.className}>
      <body>
        {children}
      </body>
    </html>
  );
}

