import AuthHeader from "@/component/authentication/AuthHeader/AuthHeader";
import LoginHeader from "@/component/LoginHeader/LoginHeader";
import Sidebar from "@/component/Sidebar/Sidebar";
import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Neural",
    description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
    return (
        
        <html lang="en">
            <body>
                <main className="">
                    <div className="grid grid-cols-12 h-screen">
                        <div className="col-span-2 border border-r-[3px] p-3"><Sidebar /></div>
                        <div className="col-span-10">
                            <div className='w-full sticky top-0 bg-white z-50 border-b-[3px]'>
                            <LoginHeader />
                            </div>
                            
                            <div>
                                {children}
                            </div>

                        </div>
                    </div>
                </main>
            </body>
        </html>
    );
}



